---
title: "Further Tests"
author: "Bin & Lizzy"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: spacelab
    toc_depth: 6
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)

DATA_PATH <- here("data/processed/prepost_cleaned_w_std_lrn_gain.csv")
REPLICATE_PATH <- here("data/processed/replicate.csv")
EVENODD_PATH <- here("data/processed/even_odd_metrics.csv")

df_all <- read_csv(DATA_PATH)
df_replicate <- read_csv(REPLICATE_PATH)
df_evenodd <- read_csv(EVENODD_PATH)
```

## Testing interaction between pretest score and condition

```{r}
raw_ck <- lm(CK_post ~ CKPK_pre*condition, df_all)
raw_pk <- lm(PK_post ~ CKPK_pre*condition, df_all)
raw_pk_diagram <- lm(PK_diagrm_post ~ CKPK_pre*condition, df_all)
raw_pk_nodiagram <- lm(PK_nodiagram_post ~ CKPK_pre*condition, df_all)

summary(raw_ck)
summary(raw_pk)
summary(raw_pk_diagram)
summary(raw_pk_nodiagram)
```

**No significant interaction between pretest and condition**

## Predicting number of problems solved from pretest and condition

```{r}
num_prob <- lm(num_solved ~ CKPK_pre*condition, data = df_replicate)

summary(num_prob)
```

